name: Telegram и HTML5-Validator
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Уведомление и валидация
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send telegram message on push
        if: github.event_name == 'push'
        uses: appleboy/telegram-action@v0.2.4  # Укажите стабильную версию
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: |
            ${{ github.actor }} создал новый коммит: ${{ github.event.head_commit.message }}
            Ссылка на коммит: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            Репозиторий: https://github.com/${{ github.repository }}
              
            CI/CD github actions: https://github.com/${{ github.repository }}/actions
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Пройти проверки HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action-experimental@v1.0.0  # Укажите стабильную версию
        with:
          root: .
        continue-on-error: true
